Adding front end
cmput404F21/CMPUT404-project-socialdistribution pull request #63
Opened 2021-11-13 05:09 UTC by Matthew-Mullen

Fixed inbox api to match expected behaviour, added front end for inbox system that matches the spec

2021-11-15 10:16 UTC, Matthew-Mullen commented
adjusted index view if user is not logged in returned to core.index.html

2021-11-25 02:26 UTC, wowikc commented on apis/inbox/views.py
> -
I would rather have that space :P

2021-11-25 02:30 UTC, wowikc commented on apps/inbox/urls.py
> +app_name = 'inbox'
that thing conflicts with app_name in apis, maybe its best to rename the URLs in api.inbox to inbox_api, and any occurrences if any (not sure)

2021-11-25 02:31 UTC, wowikc commented on apps/posts/migrations/0005_alter_post_content.py
> +# Generated by Django 3.2.9 on 2021-11-24 16:18
we probably only need on of the migrations for posts, not sure if it will cause any problems in the future

2021-11-25 02:34 UTC, wowikc requested changes
1. Can you allow that when making a post an empty categories field would be acceptable? it fails on passing a string to a list type
2. On a successful post creation, is it possible to redirect a user anywhere? either to a newly created post page or all posts page?
--Im assuming the above two also applies to editing a post--
3. We probably want a button from a specific post, that would redirect to editing. Since specifying a post by id which users don't know is not quite user friendly.  (THATs probably high priority)
4. On edit page the booleans like public/friends don't get pre-populated, which I don't know how hard would be to do with django
5. Not specifying boolean fields etc do not throw an error of any kind upon which seems weird because a user would not know what to do
6. The text content field on posts page displays as encoded string rather than original, which we probably want to convert
7. Group 10 ( I think )(which we plan to sync with) specifies both txt content and image content for one post, which could be intended by the spec, which we might need to redo later?
8. I think its better to remove all print statements which I assume are mostly for debugging
9. make/edit post still throws errors if not logged in I think?

I did not really looked into code quality and implementation only "needed functionality"

2021-11-26 00:29 UTC, wowikc commented on templates/posts/editpost.html
> +    <p>Editing the post {{post.id}}</p>
Can you please remove that line

2021-11-26 02:48 UTC, wowikc commented on templates/posts/editpost.html
> +                    document.getElementById("posttextcontent").value=atob(post.content);
that atob() tries to decode plain text content

2021-11-26 04:16 UTC, wowikc commented on templates/posts/editpost.html
> +                    document.getElementById("posttextcontent").value=atob(post.content);
resolved in a follow-up

2021-11-26 04:16 UTC, wowikc approved these changes

2021-11-26 04:16 UTC, wowikc commented
seems like we can fix it later if something

2021-11-26 04:16 UTC, merged